// Public surface of the generated API client (AD-15 / AD-16).
//
// `nexus-api-client.ts` is generated by NSwag from the Host's OpenAPI 3.0
// document (`npm run generate:api`) and is never hand-edited; CI regenerates it
// and fails on drift. This barrel is the stable, hand-written entry point so
// consumers import from `shared/api` rather than the NSwag-named file — that
// name can change without touching call sites.
//
// Re-exports the generated client classes (`AuthClient`, `Client`,
// `JobPostingsClient`), the request and response interfaces (`RegisterRequest`,
// `LoginRequest`, `AuthAccountResponse`, `CsrfTokenResponse`,
// `CreateJobPostingRequest`, `JobPostingResponse`, `ProblemDetails`) and the
// `ApiException` error type.
//
// `./http` is a hand-written sibling of the generated file: the shared HTTP
// plumbing that every `entities/*/api` and `features/*/api` slice configures its
// client with. Only the three names a slice actually needs are re-exported here
// — `createHttp` (the `fetch` factory), `callWithCsrfRetry` (the mutating-call
// wrapper), and `resetCsrfToken` (tests). The token cache, `withCredentialsAndCsrf`,
// and `isAntiforgeryFailure` stay internal to `./http`. It regenerates to
// nothing — `npm run generate:api` leaves it untouched.
export { createHttp, callWithCsrfRetry, resetCsrfToken } from './http'
export * from './nexus-api-client'
