// Public surface of the generated API client (AD-15 / AD-16).
//
// `nexus-api-client.ts` is generated by NSwag from the Host's OpenAPI 3.0
// document (`npm run generate:api`) and is never hand-edited; CI regenerates it
// and fails on drift. This barrel is the stable, hand-written entry point so
// consumers import from `shared/api` rather than the NSwag-named file — that
// name can change without touching call sites.
//
// Re-exports the generated client classes (`AuthClient`, `Client`), the request
// and response interfaces (`RegisterRequest`, `LoginRequest`,
// `AuthAccountResponse`, `CsrfTokenResponse`, `ProblemDetails`) and the
// `ApiException` error type.
export * from './nexus-api-client'
